# Generated by Django 3.2 on 2023-06-16 13:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='None', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='None', max_length=255, null=True, verbose_name='image'),
        ),
    ]
