# Generated by Django 3.2.15 on 2022-08-10 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0002_auto_20220808_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='amount_of_comments',
            field=models.ManyToManyField(blank=True, related_name='all_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='amount_of_posts',
            field=models.ManyToManyField(blank=True, related_name='all_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
