# Generated by Django 3.2.15 on 2022-08-10 16:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0005_delete_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, unique=True)),
                ('slug', models.SlugField(max_length=70, unique=True)),
                ('image', models.URLField()),
                ('amount_of_comments', models.ManyToManyField(blank=True, related_name='all_comments', to=settings.AUTH_USER_MODEL)),
                ('amount_of_posts', models.ManyToManyField(blank=True, related_name='all_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
