# Generated by Django 3.2 on 2023-06-23 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_post_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='image',
        ),
    ]
