# Generated by Django 3.2.17 on 2023-02-13 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_topic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='content.topic'),
        ),
    ]
