# Generated by Django 3.2.17 on 2023-02-14 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_post_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(default='Topics', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='content.topic'),
        ),
    ]
