# Generated by Django 3.2 on 2023-05-29 01:11

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='post_images'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='topic_images'),
        ),
    ]
