# Generated by Django 3.2 on 2023-05-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_auto_20230529_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
